name: build_under_ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code check
      uses: actions/checkout@v4

    run: sudo apt install g++
    run: sudo apt install cmake

    -name: make src code
      run: cmake -S . -B cmake-build -DCMAKE_CXX_COMPILER=g++
      run: g++ ../main.cpp -o main
