name: build_under_ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code check
      uses: actions/checkout@v4

    - name: install googletest
      run: sudo apt install -y libgoogle-glog-dev
      run: cd /usr/src/gtest
      run: sudo git clone https://github.com/google/googletest.git
      run: cd googletest
      run: sudo cmake .
      run: sudo make
      run: sudo make install

    -name: make src code
      run: cd build
      run: g++ ../main.cpp -o main
